### PR TITLE
fix for Newline is causing tag closure #1 

### LINKED ISSUE #1: Newline is causing tag closure
Newlines are automatically inserting tag closures `{/}` in color code. 
Newlines should be ignored, so we can color entire blocks just once.

### PR DESCRIPTION
**Pull request by LiamKenneth**
This works now for multi-line was a small change.

### CODE REVIEW

File: test/html.js [hunk 1]
```diff
@@ -21,6 +21,16 @@ describe('#html', function () {
     expect(result).to.equal('It is <span class="wmlime">green</span>')
   })
 
+  it('auto-closes open tags at end of multi-line string', function () {
+    const result = html('It is {lime}green\n on a new line \r another \r\n last one.')
+    expect(result).to.equal('It is <span class="wmlime">green\n on a new line \r another \r\n last one.</span>')
+  })
+
+  it('replaces colors in multi-line string', function () {
+    const result = html('It is {lime}green\n on a new line \r another \r\n last one.{/}')
```
Comment (henry-brisson) [inline test/html.js]: Thoughts on changing this so the closing tag is not actually at the end of the string (perhaps in the middle of the second line)? So that we can test the closing tag is being inserted where we want it in a multiline scenario, and ensuring it's not being caused by auto-closure.

**Review by henry-brisson — COMMENTED** [review]
This looks great, thanks! 👍 Added one small suggestion on the second test.

**Review by henry-brisson — CHANGES_REQUESTED** [review]
The `package-lock.json` file got changed substantially. Could you please revert the changes on it? It was probably caused by a different node/npm version, but I'd prefer to take a look at it in a separate PR to better understand the impacts of a version change since other apps include this lib. Thanks!

**Comment by LiamKenneth** [comment]
ignore the `package-lock.json` should not have been there. It's been reverted back now.

File: test/html.js (hunk 1 above)
Comment (LiamKenneth) [reply test/html.js]: no problem, so it's like this now if that's what you mean. Works fine still

```
 const result = html('It is {lime}green\n on a new line{/} \r another \r\n last one.')
 expect(result).to.equal('It is <span class="wmlime">green\n on a new line</span> \r another \r\n last one.')
```

**Review by henry-brisson — APPROVED** [review]
